"""empty message

Revision ID: 7011c6dacf95
Revises: d50ca923e8ae
Create Date: 2025-05-19 02:37:29.359067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7011c6dacf95'
down_revision = 'd50ca923e8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitoring_methods', sa.String(length=200), nullable=True))
        batch_op.alter_column('device_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SERVER', 'ROUTER', 'SWITCH', 'CAMERA', 'OTHER', name='devicetype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('device_type',
               existing_type=sa.Enum('SERVER', 'ROUTER', 'SWITCH', 'CAMERA', 'OTHER', name='devicetype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('monitoring_methods')

    # ### end Alembic commands ###
