"""Add last_check to Device

Revision ID: bdcdc55941b5
Revises: 7011c6dacf95
Create Date: 2025-05-20 01:56:58.787605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcdc55941b5'
down_revision = '7011c6dacf95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_check', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_check')

    # ### end Alembic commands ###
