"""Add resolved_at column to alerts

Revision ID: c470bd215a02
Revises: bdcdc55941b5
Create Date: 2025-05-20 03:57:10.060460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c470bd215a02'
down_revision = 'bdcdc55941b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_check', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('notification_sent')
        batch_op.drop_column('event_type')
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###
