"""dd device_type and check_interval columns

Revision ID: d50ca923e8ae
Revises: e005c5918bb7
Create Date: 2025-05-18 22:02:56.470760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50ca923e8ae'
down_revision = 'e005c5918bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('check_interval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('check_interval')
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###
