"""change is_online to status

Revision ID: e005c5918bb7
Revises: bedf8e71962e
Create Date: 2025-05-18 21:04:20.571101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e005c5918bb7'
down_revision = 'bedf8e71962e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=500), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('details')

    # ### end Alembic commands ###
